# image will be published to ghcr.io/<user>/<name>
name: niri-ublue
description: This is my personal OS image with niri.

base-image: ghcr.io/ublue-os/base-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

modules:
  - from-file: sddm-packages.yml
  - from-file: common-packages.yml
  - from-file: niri-packages.yml

  - from-file: common-files.yml
  - from-file: common-scripts.yml
  - from-file: sddm-scripts.yml

  - type: files
    files:
      - niri/usr: /usr

  - type: rpm-ostree
    repos:
      #- https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-39/atim-starship-fedora-39.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-40/yalter-niri-fedora-40.repo
    install:
      - distrobox
    remove:
      - toolbox
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
        - org.kde.dolphin
        - org.kde.kate
      remove:
        # - org.gnome.eog

  - type: signing
